# Generated by Django 2.2.5 on 2019-09-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20190918_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='defence',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='health',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='level',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='stamina',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='strength',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
    ]
