# Generated by Django 2.2.5 on 2019-09-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20190921_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='img',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='title',
            new_name='title_ru',
        ),
    ]
