# Generated by Django 2.2.5 on 2019-09-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20190921_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
