# Generated by Django 2.2.6 on 2019-10-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20191007_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='img_url',
            new_name='img_file',
        ),
    ]
